main: me.ferrybig.bukkit.plugins.diamondrails.DiamondRails
name: DiamondRails
version: 1.0.0
author: ferrybig
description: |
   This plugin allows mincarts that ride on a hidden track, 
   this hidden track consists from multiple blocks and can be hidden underground
load: POSTWORLD
database: false